
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/compras?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
